name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nginx-demo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Repository
        run: |
          pwd
          ls -R

      - name: Build Docker Image
        run: |
          docker build -t ${IMAGE_NAME}:latest .

      - name: Verify Docker Image
        run: |
          docker images
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          exit-code: '1'

      - name: Scan Docker Image
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            ${IMAGE_NAME}:latest
