name: CI

on:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          echo "GitHub Actions is working"
          pwd
          ls -la
